#!/bin/bash
function usage() {
cat << HELP

docker-tag  --  list all tags for a Docker image on a remote registry

EXAMPLE:
    - list all tags for ubuntu:
       docker-tag ubuntu

    - list all php tags containing apache:
       docker-tag php apache

HELP
}

if [ $# -lt 1 ]; then
	usage
	exit
fi

image="$1"
tags=$(curl -ksL https://registry.hub.docker.com/v1/repositories/${image}/tags | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}')

if [ -n "$2" ]; then
    tags=$(echo "${tags}" | grep "$2")
fi
echo "${tags}"
