#!/bin/bash
#
function usage() {
cat << HELP

harbor-image-tag  --  list all tags for a Docker image on a remote Harbor Registry

EXAMPLE:
    - list all images:
      harbor-image-tag get_images

    - list all tags for redis:
       harbor-image-tag get_tags redis/redis

HELP
}

if [ $# -lt 1 ]; then
	usage
	exit 2
fi

USER="admin"
PASS="XXXXXXXXXXXXXXXXXX"
HURL="https://{{ HARBOR_DOMAIN }}"
MTAG=$2

function get_images() {
    RTOKEN=$(curl -k -s  -u ${USER}:${PASS} ${HURL}/service/token?account=${USER}\&service=harbor-registry\&scope=registry:catalog:* | grep "token" | awk -F '"' '{print $4}')
    RLIST=$(curl -k -s -H "authorization: bearer ${RTOKEN} " ${HURL}/v2/_catalog | awk -F '[' '{print $2}'|awk -F ']' '{print $1}' | sed 's/"//g')
    echo ${RLIST} | tr ',' '\n'
}

function get_tags() {
    TTOKEN=$(curl -iksL -X GET -u ${USER}:${PASS} ${HURL}/service/token?account=${USER}\&service=harbor-registry\&scope=repository:${MTAG}:pull | grep "token" | awk -F '"' '{print $4}')
    TLIST=$(curl -ksL -X GET -H "Content-Type: application/json" -H "Authorization: Bearer ${TTOKEN}" ${HURL}/v2/${MTAG}/tags/list| awk -F '[' '{print $2}' | awk -F ']' '{print $1}' | sed 's/"//g')
    echo ${TLIST} | tr ',' '\n'
}

case $1 in
    get_images)
        get_images
        ;;
    get_tags)
        get_tags
        ;;
    *)
        usage
        ;;
esac
