apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: redis-replication
spec:
  clusterDef: redis
  componentSpecs:
  - componentDef: redis-7-1.0.1
    disableExporter: false
    name: redis
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    serviceVersion: 7.2.7
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
  - componentDef: redis-sentinel-7-1.0.1
    name: redis-sentinel
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    serviceVersion: 7.2.7
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
  terminationPolicy: Delete
  topology: replication
